import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Sidebar } from "@/components/sidebar";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen overflow-hidden border-t">
          <Sidebar className="w-64 hidden md:block" />
          <div className="flex-1 flex flex-col min-w-0 overflow-hidden">
            <ResizablePanelGroup orientation="horizontal">
              <ResizablePanel defaultSize={75} minSize={30}>
                <main className="flex-1 overflow-y-auto bg-background">
                  {children}
                </main>
              </ResizablePanel>
              <ResizableHandle withHandle />
              <ResizablePanel defaultSize={25} minSize={20}>
                <aside className="h-full border-l bg-muted/40 p-4">
                  <h3 className="font-semibold mb-4">Inspector</h3>
                  <div className="text-sm text-muted-foreground italic">
                    Agent insights and local context will appear here.
                  </div>
                </aside>
              </ResizablePanel>
            </ResizablePanelGroup>
          </div>
        </div>
      </body>
    </html>
  );
}
